'use strict';

/**
 * Structural Manus Ordering Test
 *
 * Unlike other tests that verify individual message FORMAT or match golden snapshots,
 * this test validates the STRUCTURAL RULES from bridgeTextFormat.md:
 *
 * Rule 1: Phase progression — per bridge, phases never go backwards:
 *         en-route → approaching → waiting → under-bridge → passed
 *
 * Rule 2: "inväntar" must appear before "Broöppning pågår" for each bridge
 *
 * Rule 3: No oscillation — once a bridge+phase is left, it must not return
 *         within the same passage
 *
 * Rule 4: Bridge ordering — intermediate bridges appear before their target bridge
 *         (Olidebron before Klaffbron, Stallbackabron before Stridsbergsbron)
 *
 * Rule 5: Stallbackabron never shows "inväntar broöppning"
 *
 * Rule 6: Direction-level progression — the displayed message per direction
 *         (northbound/southbound) never regresses to a less-advanced bridge+phase
 *
 * These rules are tested against ALL available AIS replay data, not just
 * curated scenarios. This catches problems that golden snapshots miss because
 * golden snapshots are generated BY the code (circular validation).
 */

const fs = require('fs');
const path = require('path');
const RealAppTestRunner = require('./journey-scenarios/RealAppTestRunner');

// ==================== CONSTANTS ====================

const LOGS_DIR = path.join(__dirname, '..', '..', 'logs');
const DEFAULT_MESSAGE = 'Inga båtar är i närheten av Klaffbron eller Stridsbergsbron';

const ALL_BRIDGES = ['Olidebron', 'Klaffbron', 'Järnvägsbron', 'Stridsbergsbron', 'Stallbackabron'];

// Phase order per manus (lower index = earlier in journey)
const PHASE_ORDER = {
  'en-route': 0,
  approaching: 1,
  'special-waiting': 2, // Stallbackabron only
  waiting: 2,
  'under-bridge': 3,
  passed: 4,
};

// Bridge order per direction (lower index = earlier in journey)
const BRIDGE_ORDER_NORTH = {
  Olidebron: 0,
  Klaffbron: 1,
  Järnvägsbron: 2,
  Stridsbergsbron: 3,
  Stallbackabron: 4,
};
const BRIDGE_ORDER_SOUTH = {
  Stallbackabron: 0,
  Stridsbergsbron: 1,
  Järnvägsbron: 2,
  Klaffbron: 3,
  Olidebron: 4,
};

// ==================== TEXT ANALYSIS HELPERS ====================

/**
 * Extract the phase from a bridge text message
 * @param {string} text - Bridge text message
 * @returns {string|null} Phase name or null
 */
function extractPhase(text) {
  if (/har precis passerat/.test(text)) return 'passed';
  if (/Broöppning pågår/.test(text)) return 'under-bridge';
  if (/passerar\s+Stallbackabron/.test(text)) return 'under-bridge';
  if (/inväntar broöppning/.test(text)) return 'waiting';
  if (/åker strax under/.test(text)) return 'special-waiting';
  if (/närmar sig/.test(text)) return 'approaching';
  if (/på väg mot/.test(text)) return 'en-route';
  return null;
}

/**
 * Extract the subject bridge (the bridge the phase applies to)
 * For "Broöppning pågår vid X" → X
 * For "närmar sig X" → X
 * For "inväntar broöppning vid/av X" → X
 * For "passerat X" → X
 * For "passerar X" → X (Stallbackabron)
 * For "åker strax under X" → X
 * For "på väg mot X" → X (en-route, but might be target not subject)
 * @param {string} text
 * @returns {string|null} Bridge name
 */
function extractSubjectBridge(text) {
  // Order matters — match most specific patterns first
  const patterns = [
    /har precis passerat\s+(Olidebron|Klaffbron|Järnvägsbron|Stridsbergsbron|Stallbackabron)/,
    /Broöppning pågår vid\s+(Olidebron|Klaffbron|Järnvägsbron|Stridsbergsbron|Stallbackabron)/,
    /passerar\s+(Stallbackabron)/,
    /inväntar broöppning\s+(?:vid|av)\s+(Olidebron|Klaffbron|Järnvägsbron|Stridsbergsbron|Stallbackabron)/,
    /åker strax under\s+(Stallbackabron)/,
    /närmar sig\s+(Olidebron|Klaffbron|Järnvägsbron|Stridsbergsbron|Stallbackabron)/,
  ];

  for (const p of patterns) {
    const m = text.match(p);
    if (m) return m[1];
  }

  // For en-route "på väg mot [bro]" the subject is the target bridge
  const enRouteMatch = text.match(/på väg mot\s+(Olidebron|Klaffbron|Järnvägsbron|Stridsbergsbron|Stallbackabron)/);
  if (enRouteMatch) return enRouteMatch[1];

  return null;
}

/**
 * Extract the destination/target bridge from the message
 * "på väg mot X" → X
 * "beräknad broöppning av X" → X
 * @param {string} text
 * @returns {string|null}
 */
function extractDestinationBridge(text) {
  // "på väg mot [bro]" — but for en-route this IS the subject, for others it's destination
  const motMatch = text.match(/på väg mot\s+(Olidebron|Klaffbron|Järnvägsbron|Stridsbergsbron|Stallbackabron)/);
  // "till [bro]" — destination in compound messages ("är på väg mot X till Y")
  const tillMatch = text.match(/\btill\s+(Olidebron|Klaffbron|Järnvägsbron|Stridsbergsbron|Stallbackabron)/);
  // "beräknad broöppning av [bro]"
  const avMatch = text.match(/beräknad broöppning av\s+(Olidebron|Klaffbron|Järnvägsbron|Stridsbergsbron|Stallbackabron)/);

  // For intermediate bridges, destination is in "till", "på väg mot" or "av"
  if (avMatch) return avMatch[1];
  if (tillMatch) return tillMatch[1];
  if (motMatch) return motMatch[1];
  return null;
}

/**
 * Infer direction from text content
 * @param {string} text
 * @returns {'northbound'|'southbound'|null}
 */
function inferDirection(text) {
  const subject = extractSubjectBridge(text);
  const dest = extractDestinationBridge(text);

  // Direct indicators
  if (subject === 'Stallbackabron') return 'southbound'; // Stallbacka only relevant southbound
  if (subject === 'Olidebron') return 'northbound'; // Olidebron only relevant northbound

  // Destination-based
  if (dest === 'Klaffbron' && (subject === 'Järnvägsbron' || subject === 'Stridsbergsbron')) return 'southbound';
  if (dest === 'Stridsbergsbron' && (subject === 'Järnvägsbron' || subject === 'Klaffbron')) return 'northbound';
  if (dest === 'Stridsbergsbron' && subject === 'Stallbackabron') return 'southbound';

  // Single bridge hints (less reliable)
  if (dest === 'Klaffbron' && subject === 'Olidebron') return 'northbound';

  return null;
}

/**
 * Calculate a combined progress score for bridge+phase in a given direction
 * Higher = more advanced in the journey
 * @param {string} bridge
 * @param {string} phase
 * @param {string} direction 'northbound'|'southbound'
 * @returns {number}
 */
function progressScore(bridge, phase, direction) {
  const bridgeOrder = direction === 'northbound' ? BRIDGE_ORDER_NORTH : BRIDGE_ORDER_SOUTH;
  const bridgeIdx = bridgeOrder[bridge];
  const phaseIdx = PHASE_ORDER[phase];

  if (bridgeIdx === undefined || phaseIdx === undefined) return -1;
  return bridgeIdx * 10 + phaseIdx;
}

// ==================== REPLAY INFRASTRUCTURE ====================

/**
 * Find all replay files with sufficient data
 */
function findReplayFiles(minLines = 50) {
  if (!fs.existsSync(LOGS_DIR)) return [];

  return fs.readdirSync(LOGS_DIR)
    .filter((f) => f.startsWith('ais-replay-') && f.endsWith('.jsonl'))
    .map((f) => path.join(LOGS_DIR, f))
    .filter((f) => {
      const lines = fs.readFileSync(f, 'utf8').split('\n').filter(Boolean);
      const sampleCount = lines.filter((l) => l.includes('[AIS_REPLAY_SAMPLE]')).length;
      return sampleCount >= minLines;
    })
    .sort(); // chronological by filename
}

/**
 * Parse a replay file into sorted samples
 */
function parseReplayFile(filePath) {
  const lines = fs.readFileSync(filePath, 'utf8').split('\n').filter(Boolean);
  return lines
    .map((line) => {
      const match = line.match(/\[AIS_REPLAY_SAMPLE\]\s+({.*})/);
      if (!match) return null;
      try {
        return JSON.parse(match[1]);
      } catch {
        return null;
      }
    })
    .filter((s) => s && Number.isFinite(s.aisTimestamp))
    .sort((a, b) => a.aisTimestamp - b.aisTimestamp);
}

/**
 * Replay a dataset and collect all bridge text changes with metadata
 */
async function replayAndCollect(runner, samples) {
  // Reset state
  const service = runner?.app?.bridgeTextService;
  if (service) {
    service._recentUnderBridgeAnnouncements?.clear?.();
    service.lastPassedMessage = null;
    service.lastPassedMessageTime = 0;
    service.lastBridgeText = '';
    service.lastBridgeTextTime = 0;
    service.lastNonDefaultText = '';
    service.lastNonDefaultTextTime = 0;
    if (typeof service.resetPhaseTracking === 'function') {
      service.resetPhaseTracking();
    }
  }
  if (runner?.app?.vesselDataService) {
    const existing = runner.app.vesselDataService.getAllVessels();
    existing.forEach((v) => runner.app.vesselDataService.removeVessel(v.mmsi, 'test-reset'));
  }
  runner.bridgeTextHistory = [];
  runner.lastBridgeText = DEFAULT_MESSAGE;
  runner.stepNumber = 0;

  const outputs = [];
  const realNow = Date.now;
  let lastText = DEFAULT_MESSAGE;

  for (const sample of samples) {
    runner.stepNumber += 1;
    Date.now = () => sample.aisTimestamp;

    try {
      await runner._processVesselAsAISMessage({
        mmsi: sample.mmsi,
        name: sample.shipName || `VESSEL_${sample.mmsi}`,
        lat: sample.lat,
        lon: sample.lon,
        sog: sample.sog,
        cog: sample.cog,
        timestamp: sample.aisTimestamp,
      });

      const currentText = runner.getCurrentBridgeText();
      if (currentText && currentText !== lastText) {
        outputs.push({
          index: outputs.length,
          timestamp: sample.aisTimestamp,
          text: currentText,
          mmsi: sample.mmsi,
          phase: extractPhase(currentText),
          subjectBridge: extractSubjectBridge(currentText),
          destinationBridge: extractDestinationBridge(currentText),
          direction: inferDirection(currentText),
        });
        lastText = currentText;
      }
    } catch {
      // Continue on error
    }
  }

  Date.now = realNow;
  return outputs;
}

// ==================== RULE VALIDATORS ====================

/**
 * Rule 1: Phase progression per bridge+direction — phases never go backwards
 * within a single passage.
 *
 * Key insight: The bridge text is a SHARED DISPLAY. Multiple vessels contribute.
 * When vessel A finishes "passerat" at a bridge and that expires, vessel B may
 * legitimately show "närmar sig" at the same bridge. This is correct behavior.
 *
 * Therefore:
 * - Track per bridge+direction (different directions are independent passages)
 * - Reset tracking after "passed" phase (passage complete, new vessel may start)
 * - Reset on DEFAULT_MESSAGE
 * - 3-minute window for same-passage detection
 */
function validatePhaseProgression(outputs) {
  const violations = [];
  // Track per bridge+direction
  const lastPhasePerBridgeDir = new Map();

  for (const output of outputs) {
    if (output.text === DEFAULT_MESSAGE) {
      lastPhasePerBridgeDir.clear();
      continue;
    }

    const { phase, subjectBridge, direction } = output;
    if (!phase || !subjectBridge) continue;

    const phaseIdx = PHASE_ORDER[phase];
    if (phaseIdx === undefined) continue;

    // Use direction if available, otherwise just bridge
    const key = direction ? `${subjectBridge}:${direction}` : subjectBridge;

    // When direction is null, we can't reliably distinguish northbound from
    // southbound passages at the same bridge. Skip regression checks for
    // null-direction entries to avoid false positives from direction switches.
    // Direction-level progression (Rule 6) handles entries with known direction.
    if (!direction) {
      lastPhasePerBridgeDir.set(key, {
        phase, phaseIdx, timestamp: output.timestamp, index: output.index,
      });
      continue;
    }

    if (lastPhasePerBridgeDir.has(key)) {
      const last = lastPhasePerBridgeDir.get(key);
      const timeDiff = output.timestamp - last.timestamp;

      // After "passed" or "under-bridge", the passage is complete/finishing.
      // A new vessel may legitimately start at an earlier phase.
      // "under-bridge" included because fast vessels may pass without
      // showing "passed" in the text (AIS gap or quick transit).
      if (last.phase === 'passed' || last.phase === 'under-bridge') {
        lastPhasePerBridgeDir.set(key, {
          phase, phaseIdx, timestamp: output.timestamp, index: output.index,
        });
        continue;
      }

      // Timeout: > 3 minutes is a new passage context
      if (timeDiff > 180000) {
        lastPhasePerBridgeDir.set(key, {
          phase, phaseIdx, timestamp: output.timestamp, index: output.index,
        });
        continue;
      }

      if (phaseIdx < last.phaseIdx) {
        violations.push({
          rule: 'PHASE_REGRESSION',
          bridge: subjectBridge,
          direction: direction || 'unknown',
          from: `${last.phase} (${last.phaseIdx})`,
          to: `${phase} (${phaseIdx})`,
          fromIndex: last.index,
          toIndex: output.index,
          fromText: outputs[last.index].text.substring(0, 90),
          toText: output.text.substring(0, 90),
          timeDiffSec: Math.round(timeDiff / 1000),
        });
      }
    }

    lastPhasePerBridgeDir.set(key, {
      phase, phaseIdx, timestamp: output.timestamp, index: output.index,
    });
  }

  return violations;
}

/**
 * Rule 2: "inväntar" must appear before "Broöppning pågår" for each bridge
 * within a single passage.
 *
 * Key insight: In multi-vessel scenarios, "Broöppning pågår" may appear
 * without a preceding "inväntar" at the same bridge if:
 * - It's the very first message about this bridge (vessel entered zone fast)
 * - A previous passage completed and a new vessel starts at under-bridge
 *
 * Only flag violations where:
 * - There ARE preceding messages about this bridge in the SAME direction
 * - No "passed" resets in between
 * - The preceding message was at an earlier phase (approaching/en-route)
 */
function validateWaitingBeforeUnderBridge(outputs) {
  const violations = [];
  // Track per bridge+direction
  const waitingShown = new Set(); // bridge:direction
  const hasEarlierPhase = new Map(); // bridge:direction → true if approaching/en-route seen

  for (const output of outputs) {
    if (output.text === DEFAULT_MESSAGE) {
      waitingShown.clear();
      hasEarlierPhase.clear();
      continue;
    }

    const { phase, subjectBridge, direction } = output;
    if (!phase || !subjectBridge) continue;

    const key = direction ? `${subjectBridge}:${direction}` : subjectBridge;

    // Track earlier phases
    if (phase === 'approaching' || phase === 'en-route') {
      hasEarlierPhase.set(key, true);
    }

    // "inväntar" or "åker strax under" counts as waiting
    if (phase === 'waiting' || phase === 'special-waiting') {
      waitingShown.add(key);
    }

    // "Broöppning pågår" without prior waiting
    if (phase === 'under-bridge') {
      // Only check if we can determine direction (otherwise we can't
      // know which passage this belongs to — different vessels in different
      // directions may have set hasEarlierPhase independently)
      if (direction) {
        if (!waitingShown.has(key) && hasEarlierPhase.has(key)) {
          violations.push({
            rule: 'MISSING_WAITING_BEFORE_UNDER_BRIDGE',
            bridge: subjectBridge,
            direction,
            index: output.index,
            text: output.text.substring(0, 90),
          });
        }
      }
    }

    // Reset tracking after passage complete
    if (phase === 'passed') {
      waitingShown.delete(key);
      hasEarlierPhase.delete(key);
    }
  }

  return violations;
}

/**
 * Rule 3: No oscillation — the same bridge+phase+direction combination
 * should not appear, then disappear, then reappear within a short window.
 *
 * Key insight: Direction changes are NOT oscillation. Bridge text may alternate
 * between northbound and southbound traffic, which is correct behavior.
 * Also, multi-vessel transitions (e.g., passed expires → next vessel shows)
 * can look like oscillation but are legitimate.
 *
 * Only flag: Same bridge + same phase + same direction appearing, then a
 * DIFFERENT bridge/phase in the SAME direction, then returning. This catches
 * the real problem: lead vessel flip-flopping.
 */
function validateNoOscillation(outputs) {
  const violations = [];
  // Track per direction to avoid cross-direction false positives
  const historyByDir = new Map(); // direction → history[]

  for (const output of outputs) {
    if (output.text === DEFAULT_MESSAGE) {
      historyByDir.clear();
      continue;
    }

    const { phase, subjectBridge, direction } = output;
    if (!phase || !subjectBridge || !direction) continue;

    const key = `${subjectBridge}:${phase}`;

    if (!historyByDir.has(direction)) {
      historyByDir.set(direction, []);
    }
    const history = historyByDir.get(direction);

    // Check for A→B→A pattern within same direction
    if (history.length >= 2) {
      for (let lookback = 2; lookback <= Math.min(4, history.length); lookback++) {
        const prev = history[history.length - lookback];
        if (prev.key === key) {
          const intermediates = history.slice(history.length - lookback + 1);
          const allDifferent = intermediates.every((h) => h.key !== key);
          if (allDifferent && intermediates.length > 0) {
            const timeDiff = output.timestamp - prev.timestamp;
            // Only flag within 2 minutes (tight window for real oscillation)
            if (timeDiff < 120000) {
              // Don't flag if:
              // - Intermediate had "passed" (legitimate cycle restart)
              // - The oscillating phase itself is "passed" (highest priority, may
              //   legitimately reappear when its window refreshes)
              const intermediateHadPassed = intermediates.some((h) => h.key.endsWith(':passed'));
              const oscillatingPhaseIsPassed = phase === 'passed';
              if (!intermediateHadPassed && !oscillatingPhaseIsPassed) {
                violations.push({
                  rule: 'OSCILLATION',
                  bridge: subjectBridge,
                  phase,
                  direction,
                  pattern: `[${prev.index}] ${prev.key} → ... → [${output.index}] ${key}`,
                  intermediates: intermediates.map((h) => `[${h.index}] ${h.key}`).join(' → '),
                  timeDiffSec: Math.round(timeDiff / 1000),
                  fromText: outputs[prev.index].text.substring(0, 80),
                  toText: output.text.substring(0, 80),
                });
              }
            }
          }
        }
      }
    }

    history.push({
      key, index: output.index, timestamp: output.timestamp,
    });
    if (history.length > 10) history.shift();
  }

  return violations;
}

/**
 * Rule 4: Bridge ordering — consecutive messages in the same direction
 * should not jump BACKWARD in bridge geography.
 *
 * Key insight: In multi-vessel replay data, different vessels are at
 * different bridges simultaneously. Global "first seen" ordering fails
 * because it conflates different vessels' journeys.
 *
 * Instead, we check CONSECUTIVE messages in the same direction:
 * If message N (direction=south) mentions bridge A at phase X,
 * and message N+1 (direction=south) mentions bridge B at phase Y,
 * and B is geographically BEFORE A in the southbound sequence,
 * AND Y is an earlier phase (not "passed" which has priority override),
 * that's a violation — the display jumped backward.
 *
 * Exception: "passed" has highest manus priority, so "passed" at an
 * earlier bridge can legitimately follow "approaching" at a later bridge.
 */
function validateBridgeOrdering(outputs) {
  const violations = [];
  // Track last bridge per direction
  const lastBridgePerDir = new Map(); // direction → { bridge, bridgeIdx, phase, index }

  for (const output of outputs) {
    if (output.text === DEFAULT_MESSAGE) {
      lastBridgePerDir.clear();
      continue;
    }

    const {
      phase, subjectBridge, direction,
    } = output;
    if (!phase || !subjectBridge || !direction) continue;

    const bridgeOrder = direction === 'northbound' ? BRIDGE_ORDER_NORTH : BRIDGE_ORDER_SOUTH;
    const bridgeIdx = bridgeOrder[subjectBridge];
    if (bridgeIdx === undefined) continue;

    if (lastBridgePerDir.has(direction)) {
      const last = lastBridgePerDir.get(direction);

      // Skip if same bridge (phase change, not bridge ordering issue)
      if (subjectBridge === last.bridge) {
        lastBridgePerDir.set(direction, {
          bridge: subjectBridge, bridgeIdx, phase, index: output.index,
        });
        continue;
      }

      // Allow "passed" at earlier bridge (highest manus priority)
      if (phase === 'passed') {
        lastBridgePerDir.set(direction, {
          bridge: subjectBridge, bridgeIdx, phase, index: output.index,
        });
        continue;
      }

      // Allow after previous "passed" (new cycle)
      if (last.phase === 'passed') {
        lastBridgePerDir.set(direction, {
          bridge: subjectBridge, bridgeIdx, phase, index: output.index,
        });
        continue;
      }

      // Allow if new message is at "en-route" phase — this indicates a
      // new vessel just entering the canal at an early bridge, which is
      // legitimate in multi-vessel scenarios
      if (phase === 'en-route') {
        lastBridgePerDir.set(direction, {
          bridge: subjectBridge, bridgeIdx, phase, index: output.index,
        });
        continue;
      }

      // Flag if new bridge is geographically BEFORE the last bridge
      if (bridgeIdx < last.bridgeIdx) {
        violations.push({
          rule: 'BRIDGE_ORDER_VIOLATION',
          direction,
          from: `${last.bridge} (idx=${last.bridgeIdx}, phase=${last.phase})`,
          to: `${subjectBridge} (idx=${bridgeIdx}, phase=${phase})`,
          fromIndex: last.index,
          toIndex: output.index,
          fromText: outputs[last.index]?.text.substring(0, 80),
          toText: output.text.substring(0, 80),
        });
      }
    }

    lastBridgePerDir.set(direction, {
      bridge: subjectBridge, bridgeIdx, phase, index: output.index,
    });
  }

  return violations;
}

/**
 * Rule 5: Stallbackabron never shows "inväntar broöppning"
 *
 * Important: Bridge text can contain semicolon-separated phrases for
 * different target bridges. "inväntar broöppning av Järnvägsbron" in one
 * phrase and "Stallbackabron" in another is NOT a violation.
 * Only flag when "inväntar" specifically refers TO Stallbackabron.
 */
function validateStallbackabronNoWaiting(outputs) {
  return outputs
    .filter((o) => {
      // Split on semicolon and check each phrase independently
      const phrases = o.text.split(';').map((p) => p.trim());
      return phrases.some((phrase) => phrase.includes('Stallbackabron')
        && /inväntar broöppning/.test(phrase));
    })
    .map((o) => ({
      rule: 'STALLBACKA_FORBIDDEN_WAITING',
      index: o.index,
      text: o.text.substring(0, 90),
    }));
}

/**
 * Rule 6: Direction-level progression — the displayed message per direction
 * should generally advance forward, not backward.
 *
 * Key insight from manus: STATUS PRIORITY determines which vessel gets
 * the display:
 *   1. Passed (HIGHEST)
 *   2. Under-bridge
 *   3. Waiting
 *   4. Approaching
 *   5. En-route (LOWEST)
 *
 * This means a "passed" at an EARLIER bridge can legitimately appear AFTER
 * "approaching" at a LATER bridge, because passed has higher status priority.
 *
 * We only flag regressions where:
 * - The new message is at a lower bridge AND lower/equal phase
 * - The previous was NOT "passed" (passage-complete allows cycle restart)
 * - Both are in the same direction
 * - Within 3 minutes (same passage context)
 */
function validateDirectionProgression(outputs) {
  const violations = [];
  const maxScore = new Map(); // direction → { score, index, bridge, phase, timestamp }

  // Manus status priority (higher = more important for display)
  const STATUS_PRIORITY = {
    'en-route': 0,
    approaching: 1,
    'special-waiting': 2,
    waiting: 2,
    'under-bridge': 3,
    passed: 4,
  };

  for (const output of outputs) {
    if (output.text === DEFAULT_MESSAGE) {
      maxScore.clear();
      continue;
    }

    const {
      phase, subjectBridge, direction,
    } = output;
    if (!phase || !subjectBridge || !direction) continue;

    const score = progressScore(subjectBridge, phase, direction);
    if (score < 0) continue;

    if (maxScore.has(direction)) {
      const prev = maxScore.get(direction);
      const timeDiff = output.timestamp - prev.timestamp;

      // Timeout: > 3 minutes is new context
      if (timeDiff > 180000) {
        maxScore.set(direction, {
          score, index: output.index, bridge: subjectBridge, phase, timestamp: output.timestamp,
        });
        continue;
      }

      // Allow after "passed" (cycle restart)
      if (prev.phase === 'passed') {
        maxScore.set(direction, {
          score, index: output.index, bridge: subjectBridge, phase, timestamp: output.timestamp,
        });
        continue;
      }

      // Allow if new message has HIGHER status priority (manus: passed > under-bridge > ...)
      // E.g., "passed" at Klaffbron can appear after "approaching" at Järnvägsbron
      const newPriority = STATUS_PRIORITY[phase] ?? -1;
      const prevPriority = STATUS_PRIORITY[prev.phase] ?? -1;
      if (newPriority > prevPriority) {
        // Higher status takes over — allowed regardless of bridge position
        maxScore.set(direction, {
          score, index: output.index, bridge: subjectBridge, phase, timestamp: output.timestamp,
        });
        continue;
      }

      if (score < prev.score) {
        violations.push({
          rule: 'DIRECTION_REGRESSION',
          direction,
          from: `${prev.bridge}:${prev.phase} (score=${prev.score})`,
          to: `${subjectBridge}:${phase} (score=${score})`,
          fromIndex: prev.index,
          toIndex: output.index,
          fromText: outputs[prev.index]?.text.substring(0, 80),
          toText: output.text.substring(0, 80),
          timeDiffSec: Math.round(timeDiff / 1000),
        });
      }

      if (score >= prev.score) {
        maxScore.set(direction, {
          score, index: output.index, bridge: subjectBridge, phase, timestamp: output.timestamp,
        });
      }
    } else {
      maxScore.set(direction, {
        score, index: output.index, bridge: subjectBridge, phase, timestamp: output.timestamp,
      });
    }
  }

  return violations;
}

// ==================== TEST SUITE ====================

describe('Structural manus ordering validation', () => {
  let runner;
  const replayFiles = findReplayFiles(50);

  beforeAll(async () => {
    if (replayFiles.length === 0) {
      console.warn('⚠️  No replay files with ≥50 samples found in logs/');
      return;
    }

    runner = new RealAppTestRunner();
    runner.setWaitMultiplier(0.1);
    runner.logLevel = 'silent';
    await runner.initializeApp();
  }, 30000);

  afterAll(async () => {
    await runner?.cleanup();
  });

  // ==================== CORE RULE TESTS ====================
  // Run against the largest replay file for maximum coverage

  const largestFile = replayFiles.length > 0
    ? replayFiles.reduce((best, f) => {
      const { size } = fs.statSync(f);
      return size > best.size ? { path: f, size } : best;
    }, { path: replayFiles[0], size: 0 }).path
    : null;

  const largestFileName = largestFile ? path.basename(largestFile) : 'none';

  describe(`Core rules (${largestFileName})`, () => {
    let outputs;

    beforeAll(async () => {
      if (!runner || !largestFile) return;
      const samples = parseReplayFile(largestFile);
      outputs = await replayAndCollect(runner, samples);
    }, 120000);

    test('Rule 1: Phase progression never regresses per bridge', () => {
      if (!outputs) return;
      const violations = validatePhaseProgression(outputs);

      if (violations.length > 0) {
        console.log(`\n❌ PHASE REGRESSION (${violations.length} violations):`);
        violations.forEach((v) => {
          console.log(`  [${v.fromIndex}→${v.toIndex}] ${v.bridge}: ${v.from} → ${v.to} (${v.timeDiffSec}s)`);
          console.log(`    FROM: ${v.fromText}`);
          console.log(`    TO:   ${v.toText}`);
        });
      }

      expect(violations).toHaveLength(0);
    });

    test('Rule 2: "inväntar/åker strax under" appears before "Broöppning pågår" per bridge', () => {
      if (!outputs) return;
      const violations = validateWaitingBeforeUnderBridge(outputs);

      if (violations.length > 0) {
        console.log(`\n❌ MISSING WAITING BEFORE UNDER-BRIDGE (${violations.length} violations):`);
        violations.forEach((v) => {
          console.log(`  [${v.index}] ${v.bridge} (${v.direction}): ${v.text}`);
        });
      }

      expect(violations).toHaveLength(0);
    });

    test('Rule 3: No oscillation (A→B→A pattern)', () => {
      if (!outputs) return;
      const violations = validateNoOscillation(outputs);

      if (violations.length > 0) {
        console.log(`\n❌ OSCILLATION (${violations.length} violations):`);
        violations.forEach((v) => {
          console.log(`  ${v.pattern} (${v.timeDiffSec}s)`);
          console.log(`    VIA: ${v.intermediates}`);
          console.log(`    FROM: ${v.fromText}`);
          console.log(`    TO:   ${v.toText}`);
        });
      }

      expect(violations).toHaveLength(0);
    });

    test('Rule 4: Bridge ordering follows geography', () => {
      if (!outputs) return;
      const violations = validateBridgeOrdering(outputs);

      if (violations.length > 0) {
        console.log(`\n❌ BRIDGE ORDER VIOLATION (${violations.length} violations):`);
        violations.forEach((v) => {
          console.log(`  ${v.direction}: Expected ${v.expected}, got ${v.actual}`);
        });
      }

      expect(violations).toHaveLength(0);
    });

    test('Rule 5: Stallbackabron never shows "inväntar broöppning"', () => {
      if (!outputs) return;
      const violations = validateStallbackabronNoWaiting(outputs);

      if (violations.length > 0) {
        console.log(`\n❌ STALLBACKA FORBIDDEN WAITING (${violations.length} violations):`);
        violations.forEach((v) => {
          console.log(`  [${v.index}] ${v.text}`);
        });
      }

      expect(violations).toHaveLength(0);
    });

    test('Rule 6: Direction-level progression never regresses', () => {
      if (!outputs) return;
      const violations = validateDirectionProgression(outputs);

      if (violations.length > 0) {
        console.log(`\n❌ DIRECTION REGRESSION (${violations.length} violations):`);
        violations.forEach((v) => {
          console.log(`  [${v.fromIndex}→${v.toIndex}] ${v.direction}: ${v.from} → ${v.to}`);
          console.log(`    FROM: ${v.fromText}`);
          console.log(`    TO:   ${v.toText}`);
        });
      }

      expect(violations).toHaveLength(0);
    });

    test('diagnostic: output summary', () => {
      if (!outputs) return;

      const nonDefault = outputs.filter((o) => o.text !== DEFAULT_MESSAGE);
      const phases = {};
      const bridges = {};
      const directions = {};

      for (const o of nonDefault) {
        if (o.phase) phases[o.phase] = (phases[o.phase] || 0) + 1;
        if (o.subjectBridge) bridges[o.subjectBridge] = (bridges[o.subjectBridge] || 0) + 1;
        if (o.direction) directions[o.direction] = (directions[o.direction] || 0) + 1;
      }

      console.log(`\n📊 Replay summary: ${outputs.length} text changes (${nonDefault.length} non-default)`);
      console.log('  Phases:', JSON.stringify(phases));
      console.log('  Bridges:', JSON.stringify(bridges));
      console.log('  Directions:', JSON.stringify(directions));

      expect(nonDefault.length).toBeGreaterThan(0);
    });
  });

  // ==================== CROSS-FILE VALIDATION ====================
  // Run rules 1 and 5 (cheapest) across ALL replay files to catch edge cases

  // Pick up to 5 files spread across the dataset for broad coverage
  const selectedFiles = (() => {
    if (replayFiles.length <= 5) return replayFiles;
    const step = Math.floor(replayFiles.length / 5);
    return [0, step, step * 2, step * 3, replayFiles.length - 1].map((i) => replayFiles[i]);
  })();

  describe.each(
    selectedFiles.map((f) => [path.basename(f), f]),
  )('Cross-file: %s', (fileName, filePath) => {
    let outputs;

    beforeAll(async () => {
      if (!runner) return;
      const samples = parseReplayFile(filePath);
      outputs = await replayAndCollect(runner, samples);
    }, 120000);

    test('no phase regression per bridge', () => {
      if (!outputs || outputs.length === 0) return;
      const violations = validatePhaseProgression(outputs);
      if (violations.length > 0) {
        console.log(`\n❌ ${fileName} — PHASE REGRESSION:`);
        violations.slice(0, 5).forEach((v) => {
          console.log(`  ${v.bridge}: ${v.from} → ${v.to}`);
        });
      }
      expect(violations).toHaveLength(0);
    });

    test('Stallbackabron never shows "inväntar"', () => {
      if (!outputs || outputs.length === 0) return;
      const violations = validateStallbackabronNoWaiting(outputs);
      expect(violations).toHaveLength(0);
    });

    test('no direction regression', () => {
      if (!outputs || outputs.length === 0) return;
      const violations = validateDirectionProgression(outputs);
      if (violations.length > 0) {
        console.log(`\n❌ ${fileName} — DIRECTION REGRESSION:`);
        violations.slice(0, 5).forEach((v) => {
          console.log(`  ${v.direction}: ${v.from} → ${v.to}`);
        });
      }
      expect(violations).toHaveLength(0);
    });
  });
});
